# .gitlab-ci.yml
#
# parity-signer
#
# pipelines can be triggered manually in the web

stages:
  - build

variables:
  GIT_STRATEGY:                    fetch
  GIT_DEPTH:                       100

default:
  cache:                           {}
  retry:
    max: 2
    when:
      - runner_system_failure
      - unknown_failure
      - api_failure

# workflow:
  # rules:
    # - if: $CI_COMMIT_TAG
    # - if: $CI_COMMIT_BRANCH

android-build:
  stage: build
  image: paritytech/signer-android-builder:latest
  rules:
      # TODO: Remove before merge with master
    - if: $CI_COMMIT_REF_NAME == "mp-ci-revamp"
    - if: $CI_COMMIT_REF_NAME =~ /^[0-9]+$/ # PRs
  artifacts:
    paths:
      - android/app/build/outputs/apk/release/app-release-unsigned.apk
  script:
    - ./scripts/build.sh android
    - cd android; ./gradlew assembleRelease
  tags:
    - linux-docker

android-build-and-sign:
  stage: build
  image: paritytech/signer-android-builder:latest
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
      # TODO: Remove before merge with master
    - if: $CI_COMMIT_REF_NAME == "mp-ci-revamp"
  artifacts:
    paths:
      - signer-ci-build.apk
  script:
    - cat "$KEYSTORE_DATA" | base64 -d > /tmp/gitlab-ci.keystore
    - wc /tmp/gitlab-ci.keystore
    - ./scripts/build.sh android
    - cd android; ./gradlew assembleRelease; cd ..
    - ./scripts/sign_android.sh /tmp/gitlab-ci.keystore "$KEYSTORE_PASS"
  tags:
    - linux-docker
