[package]
name = "qr_reader_phone"
version = "0.1.0"
authors = ["vera"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
anyhow = "1.0.65"
raptorq = "1.7.0"
serde_json = "1.0.85"
nom = "7.1.1"

[lib]
name = "qr_reader_phone"
crate-type = ["lib"]
