targets = []

[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "warn"

ignore = [
    "RUSTSEC-2024-0344",
    "RUSTSEC-2021-0139",
    "RUSTSEC-2024-0370",
    "RUSTSEC-2022-0061",
    "RUSTSEC-2020-0168",
    "RUSTSEC-2022-0081",
    "RUSTSEC-2024-0384",
    "RUSTSEC-2024-0388",
    "RUSTSEC-2024-0404",
    "RUSTSEC-2022-0093",
    "RUSTSEC-2024-0421",
    "RUSTSEC-2023-0031",
]

[licenses]
version = 2
allow = []
confidence-threshold = 0.8

[licenses.private]
ignore = false
registries = [
]

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
allow = []
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
github = [""]
gitlab = [""]
bitbucket = [""]
