# Workaround for handling skipped but required checks
# https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
name:                         Rustfmt

on:
  pull_request:
    paths:
      - '!rust/**'
  push:
    branches:
      - master
      - stable
    paths:
      - '!rust/**'

jobs:
  rustfmt:
    name:                     Cargo fmt
    runs-on:                  ubuntu-latest
    steps:
      - run: 'echo "No action required" '
