name:                   Lint & Unit Test

on:
  pull_request:
  push:
    branches:
      - master
      - stable
jobs:
  check:
    name:               Yarn
    runs-on:            ubuntu-latest
    steps:
      - name:           Checkout sources
        uses:           actions/checkout@v2
        with:
          fetch-depth:  50
      - name:           Checkout submodules
        shell:          bash
        run:            git submodule update --init --recursive
      - name:           Install NodeJS
        uses:           actions/setup-node@v1
        with:
          node-version: '15.x'
      - name:           Cache Npm
        uses:           actions/cache@v1
        with:
          path:         ~/.npm
          key:          ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name:           Get yarn cache directory path
        id:             yarn-cache-dir-path
        run:            echo "::set-output name=dir::$(yarn cache dir)"
      - name:           Cache Yarn
        uses:           actions/cache@v1
        id:             yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path:         ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key:          ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name:           Install dependencies
        run:            |
           npm install -g yarn
           yarn
      - name:           Lint
        run:            yarn lint
      - name:           Unit Test
        run:            yarn unit
      - name:           Type checking
        run:            yarn tsc
